"""FastAPI service for monitored Cats vs Dogs model inference."""

from __future__ import annotations

import csv
import logging
import os
import threading
import time
import uuid
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Annotated, AsyncIterator

import torch
from fastapi import FastAPI, File, Form, HTTPException, Request, Response, UploadFile
from pydantic import BaseModel, Field
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest

from cats_dogs_mlops.config import (
    CLASS_NAMES,
    feedback_path_from_environment,
    model_path_from_environment,
)
from cats_dogs_mlops.inference import predict_tensor
from cats_dogs_mlops.model import load_checkpoint
from cats_dogs_mlops.preprocessing import InvalidImageError, preprocess_image_bytes

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)
LOGGER = logging.getLogger("cats_dogs_api")

REQUEST_COUNT = Counter(
    "cats_dogs_http_requests_total",
    "Total HTTP requests processed by the inference service.",
    labelnames=("method", "path", "status"),
)
REQUEST_LATENCY = Histogram(
    "cats_dogs_http_request_latency_seconds",
    "HTTP request latency in seconds.",
    labelnames=("method", "path"),
)
PREDICTION_COUNT = Counter(
    "cats_dogs_predictions_total",
    "Total successful predictions by predicted class.",
    labelnames=("predicted_class",),
)
FEEDBACK_COUNT = Counter(
    "cats_dogs_feedback_total",
    "Optional labelled predictions used for post-deployment evaluation.",
    labelnames=("correct",),
)
LAST_PREDICTION_LATENCY = Gauge(
    "cats_dogs_last_prediction_latency_seconds",
    "Latency of the most recent successful model prediction.",
)

FEEDBACK_LOCK = threading.Lock()
ALLOWED_CONTENT_TYPES = {"image/jpeg", "image/jpg", "image/png", "image/webp"}


class HealthResponse(BaseModel):
    """Operational readiness returned by the health endpoint."""

    status: str
    model_loaded: bool
    model_version: str | None = None


class PredictionResponse(BaseModel):
    """Typed API contract returned for one image prediction."""

    request_id: str
    label: str
    confidence: float = Field(ge=0.0, le=1.0)
    probabilities: dict[str, float]
    model_version: str
    latency_ms: float = Field(ge=0.0)


def _normalise_true_label(true_label: str | None) -> str | None:
    """Map optional singular/plural user labels to the model vocabulary.

    Args:
        true_label: Optional label supplied with a prediction request.

    Returns:
        str | None: Canonical ``cats`` or ``dogs`` label.

    Raises:
        HTTPException: If a non-empty label is outside the supported classes.
    """

    if true_label is None or not true_label.strip():
        return None

    label = true_label.strip().lower()
    aliases = {"cat": "cats", "cats": "cats", "dog": "dogs", "dogs": "dogs"}
    if label not in aliases:
        raise HTTPException(
            status_code=422,
            detail=f"true_label must be one of: {sorted(aliases)}",
        )
    return aliases[label]


def _append_feedback(
    feedback_path: Path,
    *,
    request_id: str,
    true_label: str,
    predicted_label: str,
    confidence: float,
    model_version: str,
) -> None:
    """Append non-sensitive labelled prediction metadata to a CSV file.

    Raw image bytes, filenames, and client identifiers are deliberately not
    retained. A process-level lock prevents interleaved rows under concurrent
    requests; a production multi-worker service should use a shared database.

    Args:
        feedback_path: Destination CSV path.
        request_id: Random identifier generated by this service.
        true_label: Canonical observed class.
        predicted_label: Model output class.
        confidence: Probability assigned to the winning class.
        model_version: Version reported by the loaded checkpoint.

    Returns:
        None: One row is appended to the feedback store.
    """

    feedback_path.parent.mkdir(parents=True, exist_ok=True)
    row = {
        "timestamp_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "request_id": request_id,
        "true_label": true_label,
        "predicted_label": predicted_label,
        "confidence": f"{confidence:.6f}",
        "model_version": model_version,
    }

    with FEEDBACK_LOCK:
        file_exists = feedback_path.is_file()
        with feedback_path.open("a", newline="", encoding="utf-8") as feedback_file:
            writer = csv.DictWriter(feedback_file, fieldnames=list(row))
            if not file_exists:
                writer.writeheader()
            writer.writerow(row)


@asynccontextmanager
async def lifespan(application: FastAPI) -> AsyncIterator[None]:
    """Load the model once at startup and release references on shutdown."""

    checkpoint_path = model_path_from_environment()
    application.state.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    application.state.model = None
    application.state.model_metadata = None
    application.state.model_load_error = None

    try:
        model, metadata = load_checkpoint(checkpoint_path, application.state.device)
        application.state.model = model
        application.state.model_metadata = metadata
        LOGGER.info(
            "model_loaded path=%s version=%s sha256=%s device=%s",
            checkpoint_path,
            metadata["model_version"],
            metadata["sha256"],
            application.state.device,
        )
    except (FileNotFoundError, ValueError, RuntimeError) as exc:
        application.state.model_load_error = str(exc)
        LOGGER.exception("model_load_failed path=%s", checkpoint_path)

    yield

    application.state.model = None


app = FastAPI(
    title="Cats vs Dogs MLOps API",
    version="1.0.0",
    description="Monitored binary image-classification service for a pet adoption platform.",
    lifespan=lifespan,
)


@app.middleware("http")
async def observe_request(request: Request, call_next):
    """Measure request count and latency without logging request bodies."""

    started_at = time.perf_counter()
    status_code = 500
    try:
        response = await call_next(request)
        status_code = response.status_code
        return response
    finally:
        elapsed_seconds = time.perf_counter() - started_at
        route = request.scope.get("route")
        path_template = getattr(route, "path", request.url.path)
        REQUEST_COUNT.labels(request.method, path_template, str(status_code)).inc()
        REQUEST_LATENCY.labels(request.method, path_template).observe(elapsed_seconds)
        LOGGER.info(
            "request method=%s path=%s status=%s latency_ms=%.2f",
            request.method,
            path_template,
            status_code,
            elapsed_seconds * 1000,
        )


@app.get("/health", response_model=HealthResponse, tags=["operations"])
async def health(request: Request, response: Response) -> HealthResponse:
    """Report whether the service has loaded a usable model checkpoint."""

    if request.app.state.model is None:
        response.status_code = 503
        return HealthResponse(status="not_ready", model_loaded=False)

    metadata = request.app.state.model_metadata
    return HealthResponse(
        status="ready",
        model_loaded=True,
        model_version=str(metadata["model_version"]),
    )


@app.get("/model/info", tags=["operations"])
async def model_info(request: Request) -> dict[str, object]:
    """Return non-sensitive model provenance needed for deployment audits."""

    if request.app.state.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded")
    metadata = request.app.state.model_metadata
    return {
        "model_version": metadata["model_version"],
        "sha256": metadata["sha256"],
        "class_names": metadata["class_names"],
        "image_size": metadata["image_size"],
        "evaluation_metrics": metadata.get("metrics", {}),
    }


@app.post("/predict", response_model=PredictionResponse, tags=["inference"])
async def predict(
    request: Request,
    image: Annotated[UploadFile, File(description="JPEG, PNG, or WebP pet image")],
    true_label: Annotated[
        str | None,
        Form(description="Optional cat/dog ground truth for post-deployment tracking"),
    ] = None,
) -> PredictionResponse:
    """Classify one image and optionally record its observed label."""

    if request.app.state.model is None:
        raise HTTPException(status_code=503, detail="Model is not loaded")
    if image.content_type not in ALLOWED_CONTENT_TYPES:
        raise HTTPException(
            status_code=415,
            detail=f"Unsupported content type: {image.content_type}",
        )

    max_upload_bytes = int(os.getenv("MAX_UPLOAD_MB", "10")) * 1024 * 1024
    image_bytes = await image.read(max_upload_bytes + 1)
    await image.close()
    if len(image_bytes) > max_upload_bytes:
        raise HTTPException(status_code=413, detail="Uploaded image exceeds size limit")

    canonical_true_label = _normalise_true_label(true_label)
    metadata = request.app.state.model_metadata
    started_at = time.perf_counter()
    try:
        input_batch = preprocess_image_bytes(
            image_bytes,
            image_size=int(metadata["image_size"]),
        )
    except InvalidImageError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    prediction = predict_tensor(
        request.app.state.model,
        input_batch,
        metadata["class_names"],
        request.app.state.device,
    )
    latency_seconds = time.perf_counter() - started_at
    request_id = str(uuid.uuid4())

    predicted_label = str(prediction["label"])
    confidence = float(prediction["confidence"])
    PREDICTION_COUNT.labels(predicted_label).inc()
    LAST_PREDICTION_LATENCY.set(latency_seconds)

    if canonical_true_label is not None:
        correct = canonical_true_label == predicted_label
        FEEDBACK_COUNT.labels(str(correct).lower()).inc()
        _append_feedback(
            feedback_path_from_environment(),
            request_id=request_id,
            true_label=canonical_true_label,
            predicted_label=predicted_label,
            confidence=confidence,
            model_version=str(metadata["model_version"]),
        )

    LOGGER.info(
        "prediction request_id=%s label=%s confidence=%.4f model_version=%s latency_ms=%.2f",
        request_id,
        predicted_label,
        confidence,
        metadata["model_version"],
        latency_seconds * 1000,
    )
    return PredictionResponse(
        request_id=request_id,
        label=predicted_label,
        confidence=confidence,
        probabilities={
            str(label): float(probability)
            for label, probability in dict(prediction["probabilities"]).items()
        },
        model_version=str(metadata["model_version"]),
        latency_ms=latency_seconds * 1000,
    )


@app.get("/metrics", include_in_schema=False)
async def metrics() -> Response:
    """Expose Prometheus text-format counters and latency histograms."""

    return Response(content=generate_latest(), media_type=CONTENT_TYPE_LATEST)

